### ISSUE TITLE
Write a welcome article

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-android-dashboard#12]
Write a welcome article for the page, this first article should give a brief introduction to the product and serve as an entry point for for new users. The idea is to be able to use this for promotion.

Said article should be written in Markdown and be published in the branch of gh-pages within the folder "_post"

Steps to follow for publication:
1. Enter http://prose.io/
2. Select the Flyve MDM organization
3. Enter in repository where you want to publish the article
4. Change to the branch gh-pages
5. Click on the "NEW FILE" button
6. Write your article
7. Save your work

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Helps us to write the draft of the press release

Thanks

**Comment by Naylin15** [comment]
Hi, @ajsb85 

Here is a draft [6a19c55](https://github.com/flyve-mdm/flyve-mdm-android-admin-dashboard/commit/6a19c551d3e798902bdc9e3b86564714f3086a24)
