### ISSUE TITLE
Edit coverage 

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-android-dashboard#19]
Hi, @rafaelje 

It is necessary that all the `.html` files of the coverage have the following header:

```
---
layout: coverage
---
```
This is because the Jekyll pages used them to integrate the files into the template.

Thanks.

**Comment by ajsb85** [comment]
Hi, @rafaelje 

To-fix?
http://flyve.org/flyve-mdm-android-admin-dashboard/reports/debug/

**Comment by Naylin15** [comment]
Hi, 

I think we can close this issue, the corresponding files have the layout: coverage

Related: #28 

/cc @ajsb85 @rafaelje
