### ISSUE TITLE
Upload APK to Google Play by the API

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-dashboard#2]
Build the APK with Travis CI by tags

API Documentation
https://developers.google.com/android-publisher/api-ref/edits/apks/upload

**Comment by ajsb85** [comment]
Hi, @rafaelje 

I do not receive notifications to update from Google Play

**Comment by DIOHz0r** [comment]
@ajsb85 I got one last night, the deep link worked without problem
