### ISSUE TITLE
Add the GLPI API Client Library for Java

### ISSUE THREAD

**Issue by CamposErik** [flyve-mdm/flyve-mdm-android-dashboard#71]
**Is your feature request related to a problem? Please describe.**
Add the library to import the data.

**Comment by ag0219758** [comment]
I did not request this

**Comment by ajsb85** [comment]
Hi, @ag0219758

**Comment by CamposErik** [comment]
Could @rafaelje @Ivans51 help me with this please?

**Comment by ajsb85** [comment]
Hi, @Ivans51 
Please submit a PR in this repository adding the library.
